feat: husky ajusted

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,10 +1,3 @@
-echo "Checking for lint errors and run tests before committing..."
-
-npm run lint:fix ||
-(echo "Linting failed, please fix the lint errors before committing" && exit 1)
-
-npm run test ||
-(echo "Testing failed, please fix the test errors before committing" && exit 1)
-
-
-echo 'Done'
+#!/usr/bin/env sh
+npx --no -- lint-staged || exit 1
+npm run test || (echo "Tests failed"; exit 1)
